# Bluetooth Snaga i Odziv (Latencija)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12

# Brzina registracije pritiska (Debounce)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# N-key rollover
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Bluetooth konekcije
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

# Sleep / Idle podešavanja
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=10000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_PM_SOFT_OFF=y

# Display (nice!view)
CONFIG_ZMK_DISPLAY=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
