name: Draw Keymap
on:
  push:
    paths:
      - 'config/googootkah.keymap'
      - 'config/info.json'
      - '.github/workflows/draw.yml'
  workflow_dispatch:

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install keymap-drawer

      # 1. Prvo parsujemo ZMK keymap uz pomoć vašeg info.json fajla
      - run: |
          keymap parse \
            -z config/googootkah.keymap \
            --base-keymaps config/info.json \
            > keymap.yaml

      # 2. Zatim crtamo SVG iz sveže kreiranog keymap.yaml
      - run: keymap draw keymap.yaml > keymap.svg

      # 3. Sačuvamo novu sliku i yaml nazad na GitHub
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-update keymap SVG'
