name: Draw Keymap
on:
  push:
    paths:
      - 'config/googootkah.keymap'
      - 'config/info.json'
      - '.github/workflows/draw.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install "tree-sitter~=0.21.3" keymap-drawer

   
      - run: keymap parse -z config/googootkah.keymap > keymap.yaml

    
      - run: sed -i 's/zmk_keyboard: googootkah/qmk_keyboard: googootkah/' keymap.yaml

     
      - run: keymap draw keymap.yaml -j config/info.json > keymap.svg

    
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-update keymap SVG'
